/*
 * eHelply SDK - 1.1.79
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.79
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing AddressBase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressBaseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddressBase
        //private AddressBase instance;

        public AddressBaseTests()
        {
            // TODO uncomment below to create an instance of AddressBase
            //instance = new AddressBase();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddressBase
        /// </summary>
        [Fact]
        public void AddressBaseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddressBase
            //Assert.IsType<AddressBase>(instance);
        }


        /// <summary>
        /// Test the property 'AddressType'
        /// </summary>
        [Fact]
        public void AddressTypeTest()
        {
            // TODO unit test for the property 'AddressType'
        }
        /// <summary>
        /// Test the property 'AddressLine1'
        /// </summary>
        [Fact]
        public void AddressLine1Test()
        {
            // TODO unit test for the property 'AddressLine1'
        }
        /// <summary>
        /// Test the property 'AddressLine2'
        /// </summary>
        [Fact]
        public void AddressLine2Test()
        {
            // TODO unit test for the property 'AddressLine2'
        }
        /// <summary>
        /// Test the property 'PostalZipCode'
        /// </summary>
        [Fact]
        public void PostalZipCodeTest()
        {
            // TODO unit test for the property 'PostalZipCode'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'ProvinceState'
        /// </summary>
        [Fact]
        public void ProvinceStateTest()
        {
            // TODO unit test for the property 'ProvinceState'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Lat'
        /// </summary>
        [Fact]
        public void LatTest()
        {
            // TODO unit test for the property 'Lat'
        }
        /// <summary>
        /// Test the property 'Lng'
        /// </summary>
        [Fact]
        public void LngTest()
        {
            // TODO unit test for the property 'Lng'
        }

    }

}
