/*
 * eHelply SDK - 1.1.95
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.95
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing AlarmResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AlarmResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AlarmResponse
        //private AlarmResponse instance;

        public AlarmResponseTests()
        {
            // TODO uncomment below to create an instance of AlarmResponse
            //instance = new AlarmResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AlarmResponse
        /// </summary>
        [Fact]
        public void AlarmResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AlarmResponse
            //Assert.IsType<AlarmResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'ServiceUuid'
        /// </summary>
        [Fact]
        public void ServiceUuidTest()
        {
            // TODO unit test for the property 'ServiceUuid'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Stage'
        /// </summary>
        [Fact]
        public void StageTest()
        {
            // TODO unit test for the property 'Stage'
        }
        /// <summary>
        /// Test the property 'Process'
        /// </summary>
        [Fact]
        public void ProcessTest()
        {
            // TODO unit test for the property 'Process'
        }
        /// <summary>
        /// Test the property 'Severity'
        /// </summary>
        [Fact]
        public void SeverityTest()
        {
            // TODO unit test for the property 'Severity'
        }
        /// <summary>
        /// Test the property 'TicketUuid'
        /// </summary>
        [Fact]
        public void TicketUuidTest()
        {
            // TODO unit test for the property 'TicketUuid'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Fact]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'LatestAt'
        /// </summary>
        [Fact]
        public void LatestAtTest()
        {
            // TODO unit test for the property 'LatestAt'
        }
        /// <summary>
        /// Test the property 'AcknowledgedAt'
        /// </summary>
        [Fact]
        public void AcknowledgedAtTest()
        {
            // TODO unit test for the property 'AcknowledgedAt'
        }
        /// <summary>
        /// Test the property 'IgnoredAt'
        /// </summary>
        [Fact]
        public void IgnoredAtTest()
        {
            // TODO unit test for the property 'IgnoredAt'
        }
        /// <summary>
        /// Test the property 'ClearedAt'
        /// </summary>
        [Fact]
        public void ClearedAtTest()
        {
            // TODO unit test for the property 'ClearedAt'
        }
        /// <summary>
        /// Test the property 'TerminatedAt'
        /// </summary>
        [Fact]
        public void TerminatedAtTest()
        {
            // TODO unit test for the property 'TerminatedAt'
        }
        /// <summary>
        /// Test the property 'AssigneeUuid'
        /// </summary>
        [Fact]
        public void AssigneeUuidTest()
        {
            // TODO unit test for the property 'AssigneeUuid'
        }
        /// <summary>
        /// Test the property 'AcknowledgerUuid'
        /// </summary>
        [Fact]
        public void AcknowledgerUuidTest()
        {
            // TODO unit test for the property 'AcknowledgerUuid'
        }
        /// <summary>
        /// Test the property 'IgnorerUuid'
        /// </summary>
        [Fact]
        public void IgnorerUuidTest()
        {
            // TODO unit test for the property 'IgnorerUuid'
        }
        /// <summary>
        /// Test the property 'TerminaterUuid'
        /// </summary>
        [Fact]
        public void TerminaterUuidTest()
        {
            // TODO unit test for the property 'TerminaterUuid'
        }

    }

}
