/*
 * eHelply SDK - 1.1.112
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.112
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing AlarmAssign
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AlarmAssignTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AlarmAssign
        //private AlarmAssign instance;

        public AlarmAssignTests()
        {
            // TODO uncomment below to create an instance of AlarmAssign
            //instance = new AlarmAssign();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AlarmAssign
        /// </summary>
        [Fact]
        public void AlarmAssignInstanceTest()
        {
            // TODO uncomment below to test "IsType" AlarmAssign
            //Assert.IsType<AlarmAssign>(instance);
        }


        /// <summary>
        /// Test the property 'AssigneeUuid'
        /// </summary>
        [Fact]
        public void AssigneeUuidTest()
        {
            // TODO unit test for the property 'AssigneeUuid'
        }

    }

}
