/*
 * eHelply SDK - 1.1.118
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.118
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CatalogReturn
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CatalogReturnTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CatalogReturn
        //private CatalogReturn instance;

        public CatalogReturnTests()
        {
            // TODO uncomment below to create an instance of CatalogReturn
            //instance = new CatalogReturn();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CatalogReturn
        /// </summary>
        [Fact]
        public void CatalogReturnInstanceTest()
        {
            // TODO uncomment below to test "IsType" CatalogReturn
            //Assert.IsType<CatalogReturn>(instance);
        }


        /// <summary>
        /// Test the property 'MetaData'
        /// </summary>
        [Fact]
        public void MetaDataTest()
        {
            // TODO unit test for the property 'MetaData'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Featured'
        /// </summary>
        [Fact]
        public void FeaturedTest()
        {
            // TODO unit test for the property 'Featured'
        }
        /// <summary>
        /// Test the property 'SubCatalogs'
        /// </summary>
        [Fact]
        public void SubCatalogsTest()
        {
            // TODO unit test for the property 'SubCatalogs'
        }
        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'MetaUuid'
        /// </summary>
        [Fact]
        public void MetaUuidTest()
        {
            // TODO unit test for the property 'MetaUuid'
        }
        /// <summary>
        /// Test the property 'ProjectUuid'
        /// </summary>
        [Fact]
        public void ProjectUuidTest()
        {
            // TODO unit test for the property 'ProjectUuid'
        }
        /// <summary>
        /// Test the property 'ProductUuids'
        /// </summary>
        [Fact]
        public void ProductUuidsTest()
        {
            // TODO unit test for the property 'ProductUuids'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'DeletedAt'
        /// </summary>
        [Fact]
        public void DeletedAtTest()
        {
            // TODO unit test for the property 'DeletedAt'
        }

    }

}
