/*
 * eHelply SDK - 1.1.119
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.119
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateProjectCredit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateProjectCreditTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateProjectCredit
        //private CreateProjectCredit instance;

        public CreateProjectCreditTests()
        {
            // TODO uncomment below to create an instance of CreateProjectCredit
            //instance = new CreateProjectCredit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateProjectCredit
        /// </summary>
        [Fact]
        public void CreateProjectCreditInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateProjectCredit
            //Assert.IsType<CreateProjectCredit>(instance);
        }


        /// <summary>
        /// Test the property 'CreditsGranted'
        /// </summary>
        [Fact]
        public void CreditsGrantedTest()
        {
            // TODO unit test for the property 'CreditsGranted'
        }
        /// <summary>
        /// Test the property 'GrantedReason'
        /// </summary>
        [Fact]
        public void GrantedReasonTest()
        {
            // TODO unit test for the property 'GrantedReason'
        }

    }

}
