/*
 * eHelply SDK - 1.1.107
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.107
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DetailedMetaCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DetailedMetaCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DetailedMetaCreate
        //private DetailedMetaCreate instance;

        public DetailedMetaCreateTests()
        {
            // TODO uncomment below to create an instance of DetailedMetaCreate
            //instance = new DetailedMetaCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DetailedMetaCreate
        /// </summary>
        [Fact]
        public void DetailedMetaCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" DetailedMetaCreate
            //Assert.IsType<DetailedMetaCreate>(instance);
        }


        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
