/*
 * eHelply SDK - 1.1.114
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.114
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing GetProjectInvoiceHistory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetProjectInvoiceHistoryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetProjectInvoiceHistory
        //private GetProjectInvoiceHistory instance;

        public GetProjectInvoiceHistoryTests()
        {
            // TODO uncomment below to create an instance of GetProjectInvoiceHistory
            //instance = new GetProjectInvoiceHistory();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetProjectInvoiceHistory
        /// </summary>
        [Fact]
        public void GetProjectInvoiceHistoryInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetProjectInvoiceHistory
            //Assert.IsType<GetProjectInvoiceHistory>(instance);
        }


        /// <summary>
        /// Test the property 'ProjectUuid'
        /// </summary>
        [Fact]
        public void ProjectUuidTest()
        {
            // TODO unit test for the property 'ProjectUuid'
        }
        /// <summary>
        /// Test the property 'InvoiceHistory'
        /// </summary>
        [Fact]
        public void InvoiceHistoryTest()
        {
            // TODO unit test for the property 'InvoiceHistory'
        }

    }

}
