/*
 * eHelply SDK - 1.1.97
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.97
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing GetServiceSpecsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetServiceSpecsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetServiceSpecsResponse
        //private GetServiceSpecsResponse instance;

        public GetServiceSpecsResponseTests()
        {
            // TODO uncomment below to create an instance of GetServiceSpecsResponse
            //instance = new GetServiceSpecsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetServiceSpecsResponse
        /// </summary>
        [Fact]
        public void GetServiceSpecsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetServiceSpecsResponse
            //Assert.IsType<GetServiceSpecsResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Specs'
        /// </summary>
        [Fact]
        public void SpecsTest()
        {
            // TODO unit test for the property 'Specs'
        }

    }

}
