/*
 * eHelply SDK - 1.1.88
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.88
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing InlineResponse403
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse403Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse403
        //private InlineResponse403 instance;

        public InlineResponse403Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse403
            //instance = new InlineResponse403();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse403
        /// </summary>
        [Fact]
        public void InlineResponse403InstanceTest()
        {
            // TODO uncomment below to test "IsType" InlineResponse403
            //Assert.IsType<InlineResponse403>(instance);
        }


        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
