/*
 * eHelply SDK - 1.1.107
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.107
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing KpiResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KpiResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KpiResponse
        //private KpiResponse instance;

        public KpiResponseTests()
        {
            // TODO uncomment below to create an instance of KpiResponse
            //instance = new KpiResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KpiResponse
        /// </summary>
        [Fact]
        public void KpiResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" KpiResponse
            //Assert.IsType<KpiResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'ServiceUuid'
        /// </summary>
        [Fact]
        public void ServiceUuidTest()
        {
            // TODO unit test for the property 'ServiceUuid'
        }
        /// <summary>
        /// Test the property 'Kpis'
        /// </summary>
        [Fact]
        public void KpisTest()
        {
            // TODO unit test for the property 'Kpis'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'FetchedAt'
        /// </summary>
        [Fact]
        public void FetchedAtTest()
        {
            // TODO unit test for the property 'FetchedAt'
        }

    }

}
