/*
 * eHelply SDK - 1.1.60
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.60
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing MetaCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MetaCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MetaCreate
        //private MetaCreate instance;

        public MetaCreateTests()
        {
            // TODO uncomment below to create an instance of MetaCreate
            //instance = new MetaCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MetaCreate
        /// </summary>
        [Fact]
        public void MetaCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" MetaCreate
            //Assert.IsType<MetaCreate>(instance);
        }


        /// <summary>
        /// Test the property 'Basic'
        /// </summary>
        [Fact]
        public void BasicTest()
        {
            // TODO unit test for the property 'Basic'
        }
        /// <summary>
        /// Test the property 'Detailed'
        /// </summary>
        [Fact]
        public void DetailedTest()
        {
            // TODO unit test for the property 'Detailed'
        }
        /// <summary>
        /// Test the property 'Custom'
        /// </summary>
        [Fact]
        public void CustomTest()
        {
            // TODO unit test for the property 'Custom'
        }
        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Fact]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }
        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Fact]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }
        /// <summary>
        /// Test the property 'ParentUuid'
        /// </summary>
        [Fact]
        public void ParentUuidTest()
        {
            // TODO unit test for the property 'ParentUuid'
        }

    }

}
