/*
 * eHelply SDK - 1.1.66
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.66
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PlacesHTTPValidationError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlacesHTTPValidationErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PlacesHTTPValidationError
        //private PlacesHTTPValidationError instance;

        public PlacesHTTPValidationErrorTests()
        {
            // TODO uncomment below to create an instance of PlacesHTTPValidationError
            //instance = new PlacesHTTPValidationError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PlacesHTTPValidationError
        /// </summary>
        [Fact]
        public void PlacesHTTPValidationErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" PlacesHTTPValidationError
            //Assert.IsType<PlacesHTTPValidationError>(instance);
        }


        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Fact]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }

    }

}
