/*
 * eHelply SDK - 1.1.115
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.115
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ProjectsUsageTypeCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProjectsUsageTypeCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProjectsUsageTypeCreate
        //private ProjectsUsageTypeCreate instance;

        public ProjectsUsageTypeCreateTests()
        {
            // TODO uncomment below to create an instance of ProjectsUsageTypeCreate
            //instance = new ProjectsUsageTypeCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProjectsUsageTypeCreate
        /// </summary>
        [Fact]
        public void ProjectsUsageTypeCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProjectsUsageTypeCreate
            //Assert.IsType<ProjectsUsageTypeCreate>(instance);
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Service'
        /// </summary>
        [Fact]
        public void ServiceTest()
        {
            // TODO unit test for the property 'Service'
        }
        /// <summary>
        /// Test the property 'UnitPrices'
        /// </summary>
        [Fact]
        public void UnitPricesTest()
        {
            // TODO unit test for the property 'UnitPrices'
        }

    }

}
