/*
 * eHelply SDK - 1.1.78
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.78
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ProjectsProjectCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProjectsProjectCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProjectsProjectCreate
        //private ProjectsProjectCreate instance;

        public ProjectsProjectCreateTests()
        {
            // TODO uncomment below to create an instance of ProjectsProjectCreate
            //instance = new ProjectsProjectCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProjectsProjectCreate
        /// </summary>
        [Fact]
        public void ProjectsProjectCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProjectsProjectCreate
            //Assert.IsType<ProjectsProjectCreate>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
