/*
 * eHelply SDK - 1.1.88
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.88
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ProjectDB
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProjectDBTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProjectDB
        //private ProjectDB instance;

        public ProjectDBTests()
        {
            // TODO uncomment below to create an instance of ProjectDB
            //instance = new ProjectDB();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProjectDB
        /// </summary>
        [Fact]
        public void ProjectDBInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProjectDB
            //Assert.IsType<ProjectDB>(instance);
        }


        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'CurrentSpend'
        /// </summary>
        [Fact]
        public void CurrentSpendTest()
        {
            // TODO unit test for the property 'CurrentSpend'
        }
        /// <summary>
        /// Test the property 'MaxSpend'
        /// </summary>
        [Fact]
        public void MaxSpendTest()
        {
            // TODO unit test for the property 'MaxSpend'
        }
        /// <summary>
        /// Test the property 'ProjectStatus'
        /// </summary>
        [Fact]
        public void ProjectStatusTest()
        {
            // TODO unit test for the property 'ProjectStatus'
        }
        /// <summary>
        /// Test the property 'ArchivedAt'
        /// </summary>
        [Fact]
        public void ArchivedAtTest()
        {
            // TODO unit test for the property 'ArchivedAt'
        }

    }

}
