/*
 * eHelply SDK - 1.1.76
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.76
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SamValidationError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SamValidationErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SamValidationError
        //private SamValidationError instance;

        public SamValidationErrorTests()
        {
            // TODO uncomment below to create an instance of SamValidationError
            //instance = new SamValidationError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SamValidationError
        /// </summary>
        [Fact]
        public void SamValidationErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" SamValidationError
            //Assert.IsType<SamValidationError>(instance);
        }


        /// <summary>
        /// Test the property 'Loc'
        /// </summary>
        [Fact]
        public void LocTest()
        {
            // TODO unit test for the property 'Loc'
        }
        /// <summary>
        /// Test the property 'Msg'
        /// </summary>
        [Fact]
        public void MsgTest()
        {
            // TODO unit test for the property 'Msg'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
