/*
 * eHelply SDK - 1.1.64
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.64
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SecurityEncryptionKeyGet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SecurityEncryptionKeyGetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SecurityEncryptionKeyGet
        //private SecurityEncryptionKeyGet instance;

        public SecurityEncryptionKeyGetTests()
        {
            // TODO uncomment below to create an instance of SecurityEncryptionKeyGet
            //instance = new SecurityEncryptionKeyGet();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecurityEncryptionKeyGet
        /// </summary>
        [Fact]
        public void SecurityEncryptionKeyGetInstanceTest()
        {
            // TODO uncomment below to test "IsType" SecurityEncryptionKeyGet
            //Assert.IsType<SecurityEncryptionKeyGet>(instance);
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'RetrievedAt'
        /// </summary>
        [Fact]
        public void RetrievedAtTest()
        {
            // TODO unit test for the property 'RetrievedAt'
        }

    }

}
