/*
 * eHelply SDK - 1.1.74
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.74
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceCreate
        //private ServiceCreate instance;

        public ServiceCreateTests()
        {
            // TODO uncomment below to create an instance of ServiceCreate
            //instance = new ServiceCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceCreate
        /// </summary>
        [Fact]
        public void ServiceCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceCreate
            //Assert.IsType<ServiceCreate>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'Authors'
        /// </summary>
        [Fact]
        public void AuthorsTest()
        {
            // TODO unit test for the property 'Authors'
        }
        /// <summary>
        /// Test the property 'AuthorEmails'
        /// </summary>
        [Fact]
        public void AuthorEmailsTest()
        {
            // TODO unit test for the property 'AuthorEmails'
        }

    }

}
