/*
 * eHelply SDK - 1.1.118
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.118
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceSuperStackMetaGettingStarted
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceSuperStackMetaGettingStartedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceSuperStackMetaGettingStarted
        //private ServiceSuperStackMetaGettingStarted instance;

        public ServiceSuperStackMetaGettingStartedTests()
        {
            // TODO uncomment below to create an instance of ServiceSuperStackMetaGettingStarted
            //instance = new ServiceSuperStackMetaGettingStarted();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceSuperStackMetaGettingStarted
        /// </summary>
        [Fact]
        public void ServiceSuperStackMetaGettingStartedInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceSuperStackMetaGettingStarted
            //Assert.IsType<ServiceSuperStackMetaGettingStarted>(instance);
        }


        /// <summary>
        /// Test the property 'Blurb'
        /// </summary>
        [Fact]
        public void BlurbTest()
        {
            // TODO unit test for the property 'Blurb'
        }
        /// <summary>
        /// Test the property 'EndpointTeasers'
        /// </summary>
        [Fact]
        public void EndpointTeasersTest()
        {
            // TODO unit test for the property 'EndpointTeasers'
        }

    }

}
