/*
 * eHelply SDK - 1.1.121
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.121
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceSuperStackMetaFeature
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceSuperStackMetaFeatureTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceSuperStackMetaFeature
        //private ServiceSuperStackMetaFeature instance;

        public ServiceSuperStackMetaFeatureTests()
        {
            // TODO uncomment below to create an instance of ServiceSuperStackMetaFeature
            //instance = new ServiceSuperStackMetaFeature();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceSuperStackMetaFeature
        /// </summary>
        [Fact]
        public void ServiceSuperStackMetaFeatureInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceSuperStackMetaFeature
            //Assert.IsType<ServiceSuperStackMetaFeature>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }

    }

}
