/*
 * eHelply SDK - 1.1.77
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.77
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceResponse
        //private ServiceResponse instance;

        public ServiceResponseTests()
        {
            // TODO uncomment below to create an instance of ServiceResponse
            //instance = new ServiceResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceResponse
        /// </summary>
        [Fact]
        public void ServiceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceResponse
            //Assert.IsType<ServiceResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'Authors'
        /// </summary>
        [Fact]
        public void AuthorsTest()
        {
            // TODO unit test for the property 'Authors'
        }
        /// <summary>
        /// Test the property 'AuthorEmails'
        /// </summary>
        [Fact]
        public void AuthorEmailsTest()
        {
            // TODO unit test for the property 'AuthorEmails'
        }
        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'Heartbeats'
        /// </summary>
        [Fact]
        public void HeartbeatsTest()
        {
            // TODO unit test for the property 'Heartbeats'
        }
        /// <summary>
        /// Test the property 'Alarms'
        /// </summary>
        [Fact]
        public void AlarmsTest()
        {
            // TODO unit test for the property 'Alarms'
        }
        /// <summary>
        /// Test the property 'HiddenStages'
        /// </summary>
        [Fact]
        public void HiddenStagesTest()
        {
            // TODO unit test for the property 'HiddenStages'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
