/*
 * eHelply SDK - 1.1.118
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.118
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceSuperStackMetaFaq
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceSuperStackMetaFaqTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceSuperStackMetaFaq
        //private ServiceSuperStackMetaFaq instance;

        public ServiceSuperStackMetaFaqTests()
        {
            // TODO uncomment below to create an instance of ServiceSuperStackMetaFaq
            //instance = new ServiceSuperStackMetaFaq();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceSuperStackMetaFaq
        /// </summary>
        [Fact]
        public void ServiceSuperStackMetaFaqInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceSuperStackMetaFaq
            //Assert.IsType<ServiceSuperStackMetaFaq>(instance);
        }


        /// <summary>
        /// Test the property 'Question'
        /// </summary>
        [Fact]
        public void QuestionTest()
        {
            // TODO unit test for the property 'Question'
        }
        /// <summary>
        /// Test the property 'Answer'
        /// </summary>
        [Fact]
        public void AnswerTest()
        {
            // TODO unit test for the property 'Answer'
        }

    }

}
