/*
 * eHelply SDK - 1.1.77
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.77
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing TicketsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TicketsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TicketsResponse
        //private TicketsResponse instance;

        public TicketsResponseTests()
        {
            // TODO uncomment below to create an instance of TicketsResponse
            //instance = new TicketsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TicketsResponse
        /// </summary>
        [Fact]
        public void TicketsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TicketsResponse
            //Assert.IsType<TicketsResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'TicketId'
        /// </summary>
        [Fact]
        public void TicketIdTest()
        {
            // TODO unit test for the property 'TicketId'
        }

    }

}
