/*
 * eHelply SDK - 1.1.109
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.109
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateReview
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateReviewTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateReview
        //private UpdateReview instance;

        public UpdateReviewTests()
        {
            // TODO uncomment below to create an instance of UpdateReview
            //instance = new UpdateReview();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateReview
        /// </summary>
        [Fact]
        public void UpdateReviewInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateReview
            //Assert.IsType<UpdateReview>(instance);
        }


        /// <summary>
        /// Test the property 'Rating'
        /// </summary>
        [Fact]
        public void RatingTest()
        {
            // TODO unit test for the property 'Rating'
        }
        /// <summary>
        /// Test the property 'MaxRating'
        /// </summary>
        [Fact]
        public void MaxRatingTest()
        {
            // TODO unit test for the property 'MaxRating'
        }
        /// <summary>
        /// Test the property 'ReviewText'
        /// </summary>
        [Fact]
        public void ReviewTextTest()
        {
            // TODO unit test for the property 'ReviewText'
        }

    }

}
