/*
 * eHelply SDK - 1.1.116
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.116
 * Contact: support@ehelply.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ehelply.Sdk.Api;
using Ehelply.Sdk.Model;
using Ehelply.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ehelply.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing User
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for User
        //private User instance;

        public UserTests()
        {
            // TODO uncomment below to create an instance of User
            //instance = new User();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of User
        /// </summary>
        [Fact]
        public void UserInstanceTest()
        {
            // TODO uncomment below to test "IsType" User
            //Assert.IsType<User>(instance);
        }


        /// <summary>
        /// Test the property 'CognitoId'
        /// </summary>
        [Fact]
        public void CognitoIdTest()
        {
            // TODO unit test for the property 'CognitoId'
        }
        /// <summary>
        /// Test the property 'CognitoData'
        /// </summary>
        [Fact]
        public void CognitoDataTest()
        {
            // TODO unit test for the property 'CognitoData'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Picture'
        /// </summary>
        [Fact]
        public void PictureTest()
        {
            // TODO unit test for the property 'Picture'
        }
        /// <summary>
        /// Test the property 'GpsLocation'
        /// </summary>
        [Fact]
        public void GpsLocationTest()
        {
            // TODO unit test for the property 'GpsLocation'
        }
        /// <summary>
        /// Test the property 'VerifiedLegalTerms'
        /// </summary>
        [Fact]
        public void VerifiedLegalTermsTest()
        {
            // TODO unit test for the property 'VerifiedLegalTerms'
        }
        /// <summary>
        /// Test the property 'DateCreated'
        /// </summary>
        [Fact]
        public void DateCreatedTest()
        {
            // TODO unit test for the property 'DateCreated'
        }
        /// <summary>
        /// Test the property 'DateUpdated'
        /// </summary>
        [Fact]
        public void DateUpdatedTest()
        {
            // TODO unit test for the property 'DateUpdated'
        }
        /// <summary>
        /// Test the property 'DateDeleted'
        /// </summary>
        [Fact]
        public void DateDeletedTest()
        {
            // TODO unit test for the property 'DateDeleted'
        }
        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'LastLogin'
        /// </summary>
        [Fact]
        public void LastLoginTest()
        {
            // TODO unit test for the property 'LastLogin'
        }
        /// <summary>
        /// Test the property 'FirstLogin'
        /// </summary>
        [Fact]
        public void FirstLoginTest()
        {
            // TODO unit test for the property 'FirstLogin'
        }

    }

}
